use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// Top-level configuration file for dbhelper.
///
/// Describes the full database landscape: which engines, databases, schemas,
/// and ORM migration sources are in play.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    /// Directory where dbhelper stores computed state (compiled schemas, snapshots).
    /// Defaults to `.dbhelper/state` relative to the config file.
    #[serde(default = "default_output_dir")]
    pub output_dir: PathBuf,

    /// The databases managed by this project.
    pub databases: Vec<DatabaseConfig>,
}

fn default_output_dir() -> PathBuf {
    PathBuf::from(".dbhelper/state")
}

/// A single database (server instance or logical database).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DatabaseConfig {
    /// Logical name for this database (used in output paths and reporting).
    pub name: String,

    /// Database engine type.
    pub engine: Engine,

    /// Optional connection URL for live introspection.
    pub connection_url: Option<String>,

    /// Migration sources targeting this database.
    /// Multiple ORMs can push to the same database — dbhelper detects conflicts.
    pub sources: Vec<SourceConfig>,
}

/// Supported database engines.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Engine {
    Postgres,
    Mysql,
}

/// A single ORM migration source targeting a database.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceConfig {
    /// Which ORM generated these migrations.
    pub orm: Orm,

    /// Path to the migration files (relative to config file).
    pub migrations: PathBuf,

    /// Target schema within the database.
    /// - Postgres: defaults to "public" if omitted.
    /// - MySQL: ignored (MySQL doesn't have schemas separate from databases).
    pub schema: Option<String>,
}

/// Supported ORM migration generators.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Orm {
    Drizzle,
    #[serde(alias = "sqlalchemy")]
    Alembic,
    /// Raw SQL migration files (not generated by an ORM).
    Raw,
}

impl Config {
    /// Load a config file from the given path.
    pub fn load(path: &Path) -> Result<Self, ConfigError> {
        let contents = std::fs::read_to_string(path)
            .map_err(|e| ConfigError::Read(path.to_path_buf(), e))?;

        let config: Config = toml::from_str(&contents)
            .map_err(|e| ConfigError::Parse(path.to_path_buf(), e))?;

        config.validate()?;
        Ok(config)
    }

    /// Validate the config for logical consistency.
    fn validate(&self) -> Result<(), ConfigError> {
        if self.databases.is_empty() {
            return Err(ConfigError::Validation(
                "at least one database must be defined".into(),
            ));
        }

        let mut db_names = std::collections::HashSet::new();
        for db in &self.databases {
            if !db_names.insert(&db.name) {
                return Err(ConfigError::Validation(format!(
                    "duplicate database name: '{}'",
                    db.name
                )));
            }
            if db.sources.is_empty() {
                return Err(ConfigError::Validation(format!(
                    "database '{}' has no migration sources",
                    db.name
                )));
            }
        }

        Ok(())
    }

    /// For a given database, group sources by their target schema.
    /// This is how we detect potential conflicts — multiple sources
    /// targeting the same schema.
    pub fn sources_by_schema<'a>(
        db: &'a DatabaseConfig,
    ) -> HashMap<String, Vec<&'a SourceConfig>> {
        let mut map: HashMap<String, Vec<&'a SourceConfig>> = HashMap::new();
        for source in &db.sources {
            let schema = match db.engine {
                Engine::Postgres => source
                    .schema
                    .clone()
                    .unwrap_or_else(|| "public".to_string()),
                Engine::Mysql => db.name.clone(),
            };
            map.entry(schema).or_default().push(source);
        }
        map
    }
}

#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error("failed to read config file {0}: {1}")]
    Read(PathBuf, std::io::Error),

    #[error("failed to parse config file {0}: {1}")]
    Parse(PathBuf, toml::de::Error),

    #[error("config validation error: {0}")]
    Validation(String),
}
